#include "TestYtDlpArgsBuilder.h" // Include the new header
#include <QUrl> // Add QUrl include
#include "core/YtDlpArgsBuilder.h"
#include "core/ConfigManager.h"
#include "BaseTest.h" // Include BaseTest, now in src/tests


void TestYtDlpArgsBuilder::testBasicVideoArguments() {
    ConfigManager *mockConfig = getConfigManager();
    mockConfig->set("General", "restrict_filenames", true);
    mockConfig->set("Video", "video_quality", "best");
    mockConfig->set("Video", "video_extension", "mp4");
    mockConfig->set("Video", "video_codec", "Default"); // Explicitly set to Default
    mockConfig->set("Video", "video_audio_codec", "Default"); // Explicitly set to Default

    YtDlpArgsBuilder builder; // Use default constructor

    QVariantMap options;
    options["type"] = "video";
    options["videoQuality"] = "best";
    options["videoExtension"] = "mp4";
    // Add other relevant options here if needed for specific tests

    QStringList args = builder.build(mockConfig, QUrl("https://www.youtube.com/watch?v=dQw4w9WgXcQ").toString(), options);

    QString expectedFormatArg = "bestvideo+bestaudio/bestvideo+bestaudio/bestvideo+bestaudio/bestvideo+bestaudio/bestvideo/bestvideo/best";

    QVERIFY(args.contains("--ignore-config"));
    QVERIFY(args.contains("--restrict-filenames")); // Now this should be true
    QVERIFY(args.contains("https://www.youtube.com/watch?v=dQw4w9WgXcQ"));
    QVERIFY(args.contains("-f"));
    QVERIFY(args.contains(expectedFormatArg)); // Check for the expected simple format
    QVERIFY(args.contains("--merge-output-format"));
    QVERIFY(args.contains("mp4"));
}

void TestYtDlpArgsBuilder::testSponsorBlockArguments() {
    ConfigManager *mockConfig = getConfigManager();
    mockConfig->set("General", "sponsorblock", true); // Enable SponsorBlock
    mockConfig->set("Video", "video_quality", "best");
    mockConfig->set("Video", "video_extension", "mp4");

    YtDlpArgsBuilder builder; // Use default constructor

    QVariantMap options;
    options["type"] = "video";
    options["videoQuality"] = "best";
    options["videoExtension"] = "mp4";
    // Add other relevant options here if needed for specific tests

    QStringList args = builder.build(mockConfig, QUrl("https://www.youtube.com/watch?v=dQw4w9WgXcQ").toString(), options);

    QVERIFY(args.contains("--sponsorblock-remove"));
    QVERIFY(args.contains("all"));
    QVERIFY(args.contains("--force-keyframes-at-cuts"));
}

// Generates the main() function for the test executable
QTEST_MAIN(TestYtDlpArgsBuilder)

// Includes the moc file generated by Qt
#include "TestYtDlpArgsBuilder.moc"